### ISSUE TITLE
Tab completion on Athena Console

### ISSUE THREAD

**Issue by paulocoghi** [athena-framework/athena#293]
Hello Athena community,

I would like to ask if there is a way to intercept a "tab completion" attempt in Athena Console, in order to programmatically decide what to add/complete, if the context is appropriate.

**Comment by Blacksmoke16** [comment]
At the moment, no. But the feature is planned at some point and just needs to be implemented: https://athenaframework.org/Console/Question/#Athena::Console::Question--autocompletion. Which would function similary to https://symfony.com/blog/new-in-symfony-5-4-console-autocompletion.

However, when going to execute a command, aliases may be a decent workaround. The console component is kinda smart and it'll guess what you mean and if there is no ambiguity, execute it even if its not a 100% match.

E.g. if you have commands `foo:bar` and `foo:foo`. Executing command `f:f` would work since there is only one possibility for it.
